apiVersion: batch/v1
kind: Job
metadata:
  name: localstack-init
spec:
  template:
    spec:
      containers:
        - name: init
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - |
              aws configure set aws_access_key_id test && \
              aws configure set aws_secret_access_key test && \
              aws configure set region us-east-1 && \
              until curl -s http://localstack:4566; do sleep 1; done && \
              aws --endpoint-url=http://localstack:4566 s3 mb s3://mlflow-artifacts || true && \
              aws --endpoint-url=http://localstack:4566 s3api put-bucket-cors \
                --bucket mlflow-artifacts \
                --cors-configuration file:///tmp/cors.json || true
          volumeMounts:
            - name: cors-config
              mountPath: /tmp/cors.json
              subPath: cors.json
      restartPolicy: OnFailure
      volumes:
        - name: cors-config
          configMap:
            name: localstack-cors